<a href="https://colab.research.google.com/github/raviraj2833/python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


List vs NumPy - Time taken


In [2]:
from time import process_time


Time taken by a list


In [8]:
python_list=[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for i in python_list]

end_time=process_time()

print(end_time - start_time)


0.0015069119999999714


In [16]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()

np_array+=5

end_time=process_time()

print(end_time - start_time)


0.0012726079999989537


Numpy Array


In [17]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [18]:
#NumPy array
NumPy=np.array([1,2,3,4,5])
print(NumPy)
type(NumPy)

[1 2 3 4 5]


numpy.ndarray

One dimensional vs two dimensional array

In [20]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [21]:
a.shape

(4,)

In [24]:
b=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
b.shape

(3, 3)

Initial the placeholder of NumPy array


In [26]:
# create a numpy array of zeros
c=np.zeros((4,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
c=np.ones((4,5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
#create an Identity matrix
i=np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [43]:
#create a numpy array with random value
ran=np.random.random((3,4))
print(ran)

[[5.60364012 9.34548296 2.02642713 0.88533176]
 [0.78603157 6.67442333 7.13776175 2.61077376]
 [8.26368749 3.04282116 1.19086363 9.04271262]]


In [55]:
#create an numpy arrat with random value in specific integer value
ran2=np.random.randint(1,5,(2,2))
print(ran2)

[[1 3]
 [2 4]]


In [59]:
#create a numpy array for evenly space-->> specifying he number of values required
e=np.linspace(10,30,6)
print(e)

[10. 14. 18. 22. 26. 30.]


In [71]:
#create a numpy array for aranging the step --->>> specifying the step
k=np.arange(4,21,4)
print(k)

[ 4  8 12 16 20]


In [75]:
#convert list into numPy
list3=[1,2,3,4,5]
# type(list3)
print(type(list3))
np_array=np.asarray(list3)
print(np_array)
print(type(np_array))


<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


Annalyzing the numPy array


In [78]:
l=np.random.randint(1,100,(9,4))
print(l)


[[91 75 28 34]
 [98 51 53 68]
 [30 55 12 72]
 [41 45 91 63]
 [34 78 41 44]
 [58 27 92 92]
 [56 59 54 47]
 [34 82 81 62]
 [91 78 54 29]]


In [79]:
# array dimension
print(l.shape)

(9, 4)
